# Generated by Django 5.0.3 on 2024-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(),
        ),
    ]
