# Generated by Django 5.0.3 on 2024-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
